name: secure_messenger
description: Military-grade encrypted messaging application with anonymous identities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  go_router: ^13.2.2
  crypto: ^3.0.3
  cryptography:  2.7.0 
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  dio: ^5.4.3+1
  qr_flutter: ^4.1.0
  local_auth: ^2.1.7
  permission_handler: ^11.3.0
  uuid: ^4.3.3
  intl: ^0.20.0
  path_provider: ^2.1.2
  device_info_plus: ^10.1.0
  flutter_jailbreak_detection: ^1.10.0
  socks5_proxy: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10
  argon2: ^1.0.1
  image_picker: ^1.0.7
  file_picker: ^10.2.0
  image: ^4.1.3
  flutter_colorpicker: ^1.0.3
  restart_app: ^1.2.1
  pin_code_fields: ^8.0.1
  passcode_screen: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/app_logo.svg
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/images/wallpapers/
